driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  # https://github.com/chef/bento
  # - name: debian-7.8 # cannot get dependencies satisfied
  - name: debian-8.1

  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-14.10
  - name: ubuntu-15.04

suites:
  - name: default
    run_list:
      - recipe[test::install_apt_https]
      - recipe[apt-docker]
      - recipe[test::install_docker]

  - name: testing
    run_list:
      - recipe[test::install_apt_https]
      - recipe[apt-docker]
      - recipe[test::install_docker]
    excludes:
      - ubuntu-14.10 # test fails, no candidate version available
    attributes:
      apt-docker:
        repos:
          docker-main:
            managed: false
          docker-testing:
            managed: true
          docker-experimental:
            managed: false

  - name: experimental
    run_list:
      - recipe[test::install_apt_https]
      - recipe[apt-docker]
      - recipe[test::install_docker]
    attributes:
      apt-docker:
        repos:
          docker-main:
            managed: false
          docker-testing:
            managed: false
          docker-experimental:
            managed: true
